spring:
  datasource:
    url: "jdbc:h2:file:./h2/database;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

example:
  audiohive:
    default-admin:
      name: admin
      password: admin123